adding die to each script part

diff --git a/general/buildcheck b/general/buildcheck
--- a/general/buildcheck
+++ b/general/buildcheck
@@ -2,6 +2,12 @@
 BASEDIR=$(dirname "$(readlink -f "$0")")
 SOLUTION=$(readlink -f *.sln)
 
-[ -z "$SOLUTION" ] && echo "No Solution found in $(pwd)" && exit 1
+die() {
+    echo
+    echo "$@"
+    exit 1
+}
 
-dotnet buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild true
+[ -z "$SOLUTION" ] && die "No Solution found in $(pwd)"
+
+dotnet buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild true || die "Check failed"
diff --git a/general/buildtest b/general/buildtest
--- a/general/buildtest
+++ b/general/buildtest
@@ -1,6 +1,13 @@
 #! /bin/sh
 BASEDIR=$(dirname "$(readlink -f "$0")")
 
+die() {
+    echo
+    echo "$@"
+    exit 1
+}
+
+
 CLEAR="http-cache"
   while [ $# -gt 0 ]; do
     key="$1"
@@ -16,37 +23,36 @@ CLEAR="http-cache"
     esac
   done
 
-echo "***** Clearing NuGet cache ($CLEAR)... *****" && \
-  dotnet nuget locals "$CLEAR" --clear && \
-  echo "***** Restoring... *****" && \
-  dotnet tool restore && \
-  echo "***** Checking... *****" && \
-  $BASEDIR/buildcheck && \
-  echo "***** Restoring... *****" && \
-  dotnet restore && \
-  echo "***** Cleaning... *****" && \
-  dotnet clean && \
-  echo "***** Building... *****" && \
-  dotnet build \
-            --configuration Release \
-            "-p:Version=0.0.0.1-test" \
-            "-p:IsProduction=false" \
-            -p:ApiCompatGenerateSuppressionFile=true \
-            -nodeReuse:False \
-            -p:NoWarn=MSB4241 \
-            -p:SuppressNETCoreSdkPreviewMessage=true \
-            -p:Optimize=true && \
-  echo "***** Testing... *****" && \
-  dotnet test \
-            -noConsoleLogger \
-            --configuration Release \
-            "-p:Version=0.0.0.1-test" \
-            "-p:IsProduction=false" \
-            --filter FullyQualifiedName\!~Integration \
-            --logger:"trx;LogFilePrefix=testResults" \
-            -p:ApiCompatGenerateSuppressionFile=true \
-            -nodeReuse:False \
-            -p:NoWarn=MSB4241 \
-            -p:SuppressNETCoreSdkPreviewMessage=true \
-            -p:Optimize=true && \
-  echo "***** Completed *****"
+echo "***** Clearing NuGet cache ($CLEAR)... *****" 
+dotnet nuget locals "$CLEAR" --clear  || die "######## Nuget Clear $CLEAR Failed ########"
+echo "***** Restoring... *****" 
+dotnet tool restore  || die "######## Tool Restore Failed ########"
+echo "***** Checking... *****" 
+$BASEDIR/buildcheck  || die "######## Build Check Failed ########"
+echo "***** Restoring... *****" 
+dotnet restore  || die "######## Restore Failed ########"
+echo "***** Cleaning... *****" 
+dotnet clean  || die "######## Clean Failed ########"
+echo "***** Building... *****" 
+dotnet build \
+          --configuration Release \
+          "-p:Version=0.0.0.1-test" \
+          "-p:IsProduction=false" \
+          -p:ApiCompatGenerateSuppressionFile=true \
+          -nodeReuse:False \
+          -p:NoWarn=MSB4241 \
+          -p:SuppressNETCoreSdkPreviewMessage=true \
+          -p:Optimize=true || die "######## Build Failed ########"
+echo "***** Testing... *****" 
+dotnet test \
+          -noConsoleLogger \
+          --configuration Release \
+          "-p:Version=0.0.0.1-test" \
+          "-p:IsProduction=false" \
+          --filter FullyQualifiedName\!~Integration \
+          -p:ApiCompatGenerateSuppressionFile=true \
+          -nodeReuse:False \
+          -p:NoWarn=MSB4241 \
+          -p:SuppressNETCoreSdkPreviewMessage=true \
+          -p:Optimize=true || die "######## Tests Failed ########"
+  echo "***** Completed *****" 
