curl retry times

diff --git a/general/install-latest-dotnet b/general/install-latest-dotnet
--- a/general/install-latest-dotnet
+++ b/general/install-latest-dotnet
@@ -144,16 +144,16 @@ set -e
 get_latest_dotnet_sdk_version() {
     DOTNET_CHANNEL_VERSION=$1
     [ -z "$DOTNET_CHANNEL_VERSION" ] && die "Dotnet channel version not defined" 
-    curl --connect-timeout 5 \
-         --max-time 10 \
-         --retry 5 \
-         --retry-delay 1 \
-         --retry-max-time 40 \
-         -s \
-         -L \
-         -f \
-         --user-agent "$USER_AGENT" \
-         https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json |
+    curl \
+       --max-time 120 \
+       --retry 5 \
+       --retry-delay 0 \
+       --retry-max-time 600 \
+       -s \
+       -L \
+       -f \
+       --user-agent "$USER_AGENT" \
+       https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json |
     jq --arg v "$DOTNET_CHANNEL_VERSION" -r '
             ."releases-index" 
             | map(select(."channel-version" | contains($v)))
@@ -203,16 +203,17 @@ for VERSION in $VERSIONS_TO_INSTALL; do
   echo "**********************************************************************************************"
   echo ""
   DOWNLOAD_URL=$DOWNLOAD_SOURCE/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-x64.tar.gz
-  curl --max-time 10 \
-       --retry 5 \
-       --retry-delay 1 \
-       --retry-max-time 40 \
-       -s \
-       -L \
-       -f \
-       --user-agent "$USER_AGENT" \
-       "$DOWNLOAD_URL" \
-       -o "$TEMPORARY_FILE" || die "Could not download: $DOWNLOAD_URL"  
+  curl \
+    --max-time 120 \
+    --retry 5 \
+    --retry-delay 0 \
+    --retry-max-time 600 \
+    -s \
+    -L \
+    -f \
+    --user-agent "$USER_AGENT" \
+    "$DOWNLOAD_URL" \
+    -o "$TEMPORARY_FILE" || die "Could not download: $DOWNLOAD_URL"  
 
   extract_dotnet_package "$TEMPORARY_FILE" "/usr/share/dotnet" || die "Could not install" 
   
