Using local cache rather than hitting the upstream all the time

diff --git a/general/install-latest-dotnet b/general/install-latest-dotnet
--- a/general/install-latest-dotnet
+++ b/general/install-latest-dotnet
@@ -10,10 +10,20 @@ BASEDIR=$(dirname "$(readlink -f "$0")")
 
 [ -z "$BASEDIR" ] && die "BASEDIR Not defiled"  
 
+PROXY_HOST=http://builds.dotnet.local:5554/dotnet
 
 # update dotnet install scripts
-wget https://dot.net/v1/dotnet-install.sh -O "$BASEDIR/dotnet-install.sh"
-[ ! -f "$BASEDIR/dotnet-install.sh" ] && die "dotnet install script failed"
+
+[ -f "$BASEDIR/dotnet-install.sh" ] && rm -f"$BASEDIR/dotnet-install.sh"
+echo "Downloading Latest install script"
+curl https://dot.net/v1/dotnet-install.sh -L -f -o "$BASEDIR/dotnet-install.sh" || die "Could not download install script"
+[ -f "$BASEDIR/dotnet-install.sh" ] || die "dotnet install script failed"
+
+echo "Changing install script to use local proxy cache.."
+sed -i "s|https://builds.dotnet.microsoft.com/dotnet|$PROXY_HOST|g" "$BASEDIR/dotnet-install.sh"
+sed -i "s|https://ci.dot.net/public|$PROXY_HOST/dotnet|g" "$BASEDIR/dotnet-install.sh"
+#sed -i "s|https://aka.ms/dotnet|https://builds.dotnet.local:5555/dotnet|g" "$BASEDIR/dotnet-install.sh"
+echo "Changing install script to use local proxy cache..."
 
 chmod +x "$BASEDIR/dotnet-install.sh"
 
@@ -28,4 +38,4 @@ sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 9.0
 # Install/update powershell
 sudo /usr/share/dotnet/dotnet tool update --local PowerShell
 
-rm -f "$BASEDIR/dotnet-install.sh"
+# rm -f "$BASEDIR/dotnet-install.sh"
