THis one deploys something that works already

diff --git a/general/restore-all b/general/restore-all
--- a/general/restore-all
+++ b/general/restore-all
@@ -5,8 +5,6 @@ dotnet nuget locals all --clear
 
 echo "Restoring packages"
 find "$HOME/work" -iname global.json | while read -r key; do
-  CURRENT_DIR=$(dirname "$key")
-  echo "* $CURRENT_DIR:"
-  cd "$CURRENT_DIR" && dotnet restore && echo "   * done" || echo "   * failed"   
-  
+  CURRENT_DIR=$(dirname "$key");
+  echo "* $CURRENT_DIR:" &&  cd "$CURRENT_DIR" && dotnet restore && echo "   * done" || echo "   * failed";     
 done 
