DB scripts pass shellcheck

diff --git a/db/install-mssql b/db/install-mssql
--- a/db/install-mssql
+++ b/db/install-mssql
@@ -1,7 +1,5 @@
 #! /bin/sh
 
-PROG=$0
-
 die() {
     echo
     echo "$@"
@@ -13,6 +11,8 @@ echo "Script Dir: $BASEDIR"
 
 cd "$BASEDIR" || die "Could not select $BASEDIR"
 
+# Not following: 
+# shellcheck disable=1091
 . "$BASEDIR/dbenv"
 
 SHARED_DATA=/db/mssql/
@@ -36,18 +36,18 @@ done
 
 
 echo "Ensuring Data exists"
-sudo mkdir -p $SHARED_DATA/data
-sudo mkdir -p $SHARED_DATA/logs
-sudo mkdir -p $SHARED_DATA/secrets
+sudo mkdir -p "$SHARED_DATA/data"
+sudo mkdir -p "$SHARED_DATA/logs"
+sudo mkdir -p "$SHARED_DATA/secrets"
 
 echo "Ensuring docker has permission to access $SHARED_DATA"
-sudo chown -R 10001:docker $SHARED_DATA
-sudo chmod -R 700 $SHARED_DATA
+sudo chown -R 10001:docker "$SHARED_DATA"
+sudo chmod -R 700 "$SHARED_DATA"
 
 {
   echo "PASSWORD=$PASSWORD"
   echo "SHARED_DATA=$SHARED_DATA"
-} > ""$BASEDIR/.env""
-sudo docker compose pull
-sudo docker compose up -d
-rm -f ""$BASEDIR/.env""
+} > "$BASEDIR/.env"
+sudo docker compose pull || die "Could not get mssql container"
+sudo docker compose up -d || die "Could not start mssql"
+rm -f "$BASEDIR/.env"
