Use docker-compose

diff --git a/db/install-mssql b/db/install-mssql
--- a/db/install-mssql
+++ b/db/install-mssql
@@ -11,10 +11,11 @@ die() {
 BASEDIR="$(dirname "$(readlink -f "$0")")"
 echo "Script Dir: $BASEDIR"
 
+cd "$BASEDIR" || die "Could not select $BASEDIR"
 
 . "$BASEDIR/dbenv"
 
-SHARED_DATA=
+SHARED_DATA=/db/mssql/
 while [ $# -gt 0 ]; do
   key="$1"
 
@@ -33,24 +34,10 @@ done
 [ -z "$PASSWORD" ] && die "--password not specified"
 [ -z "$SHARED_DATA" ] && die "--data not specified"
 
-echo "Ensuring network installed"
-sudo docker network create multi-host-network
-
-DOCKERIMAGE=mcr.microsoft.com/mssql/server:2022-latest
-echo "Getting container from registry"
-sudo docker pull $DOCKERIMAGE
-
-echo "Ensuring Data exists"
-sudo mkdir -p $SHARED_DATA/.db/data
-sudo mkdir -p $SHARED_DATA/.db/logs
-sudo mkdir -p $SHARED_DATA/.db/secrets
-
-echo "Ensuring docker has permission to access $SHARED_DATA"
-sudo chown -R 10001:docker $SHARED_DATA
-sudo chmod -R 700 $SHARED_DATA
- 
-echo "Installing container"
-sudo docker container stop mssql
-sudo docker container rm mssql
-
-sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$PASSWORD" -e "MSSQL_PID=Developer" -p 1433:1433  --name mssql --hostname sql -v $SHARED_DATA/.db/data:/var/opt/mssql/data -v $SHARED_DATA/.db/logs:/var/opt/mssql/logs -v $SHARED_DATA/.db/secrets:/var/opt/mssql/secrets -v/home:/home --network multi-host-network --restart always -d $DOCKERIMAGE
+{
+  echo "PASSWORD=$PASSWORD"
+  echo "SHARED_DATA=$SHARED_DATA"
+} > ""$BASEDIR/.env""
+sudo docker compose pull
+sudo docker compose up -d
+rm -f ""$BASEDIR/.env""
